SystemDiskSize: 40
RuntimeType: Container
ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: aliyun-computenest/quickstart-code-server
DockerComposeEnvPath: .env
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: true
  Type: String
  Description: ''
  Required: true
  AllowedPattern: ''
  Label: CodeServer服务登录密码
  ConstraintDescription: ''
  Name: CODE_SERVER_PASSWORD
DockerComposeYamlPath: docker-compose.yaml
Owner: Alicloud-ComputeNest
Branch: main
Platform: github
